version: "3.5"
services:
  g2n:
    image: gmail2nag
    environment:
      - GM_URL=imap.gmail.com
      - GM_MAILBOX_NAME=monitor_spam
      - GM_MAIL_STATUS=UNSEEN
      - GM_USERNAME=jeremy.yung@icmanage.com
      - GM_API_PW=zeilvzlgjqiozsxx
      - TZ=America/Los_Angeles
    volumes: 
      - g2n_db:/opt/g2nout
    container_name: g2n
  
  nagios:
    image: nagios-g2n
    ports:
      - "0.0.0.0:8080:80"
    environment:
      #NAGIOSADMIN env variables sets credentials that let you log into Nagios GUI.
      - NAGIOSADMIN_USER=icmAdmin
      - NAGIOSADMIN_PASS=icmAdmin
      - G2N_FILE=/opt/g2nout/g2n.json
      - TZ=America/Los_Angeles
    volumes:
      - nag:/opt/nagios
      - nag_etc:/opt/nagios/etc
      - nag_libexec:/opt/nagios/libexec
      - nag_ssmtp:/etc/ssmtp
      - nag_var:/opt/nagios/var #makes status.dat file (comments, status info, etc.) persistant
      - g2n_db:/opt/g2nout
    container_name: nagios

volumes:
  g2n_db:
  nag:
  nag_etc:
  nag_libexec:
  nag_ssmtp:
  nag_var:

